[build]
  command = "npm run build"  # Asegúrese de ajustar esto según sus necesidades

[functions]
  command = { directory = "functions", handler = "index.handler" }


[dev]
  # ... (otras configuraciones)